# Generated by Django 3.1.2 on 2022-08-27 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TemperatureMeasurement',
            new_name='Measurement',
        ),
    ]
